import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#F8F9FA",
  },
  container: {
    flex: 1,
  },
  header: {
    backgroundColor: "white",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    paddingBottom: 8,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 8,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  headerCenter: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  headerIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#E3F2FD",
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1a1a1a",
  },
  subtitle: {
    fontSize: 11,
    color: "#666",
    marginTop: 1,
    fontWeight: "600",
  },
  refreshButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#E3F2FD",
    alignItems: "center",
    justifyContent: "center",
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#E3F2FD",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  searchInputModal: {
    fontSize: 16,
    color: "#1a1a1a",
    fontWeight: "500",
    borderWidth: 1,
    borderColor: "#e9ecef",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginBottom: 8,
    backgroundColor: "#fafafa",
  },
  filterTabsWrapperCompact: {
    flexDirection: "row",
    gap: 4,
    paddingHorizontal: 16,
    marginTop: 0,
    marginBottom: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  filterTabCompact: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 7,
    backgroundColor: "white",
    borderWidth: 1.2,
    borderColor: "#E0E0E0",
    minWidth: 0,
    marginHorizontal: 0,
    gap: 4,
  },
  filterTabActive: {
    backgroundColor: "#2196F3",
    borderColor: "#2196F3",
  },
  filterTabOngoing: {
    backgroundColor: "#4CAF50",
    borderColor: "#4CAF50",
  },
  filterTabTextCompact: {
    fontSize: 12,
    fontWeight: "700",
    color: "#666",
    marginRight: 2,
  },
  filterTabTextActive: {
    color: "white",
  },
  filterBadgeCompact: {
    backgroundColor: "#F0F0F0",
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 3,
    marginLeft: 2,
  },
  filterBadgeActive: {
    backgroundColor: "rgba(255,255,255,0.3)",
  },
  filterBadgeTextCompact: {
    fontSize: 11,
    fontWeight: "800",
    color: "#666",
    paddingHorizontal: 1,
  },
  filterBadgeTextActive: {
    color: "white",
  },
  filtersScroll: {
    flexGrow: 0,
    flexShrink: 0,
    height: 40,
  },
  filtersScrollContent: {
    paddingHorizontal: 16,
    gap: 6,
    alignItems: "flex-start",
  },
  filterChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#e9ecef",
    gap: 4,
  },
  filterChipActive: {
    backgroundColor: "#2196F3",
    borderColor: "#2196F3",
  },
  filterChipText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#666",
  },
  filterChipTextActive: {
    color: "white",
  },
  filterChipReset: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFEBEE",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#E53935",
    gap: 4,
  },
  filterChipResetText: {
    fontSize: 12,
    fontWeight: "800",
    color: "#E53935",
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  loadingText: {
    fontSize: 16,
    color: "#666",
    fontWeight: "600",
  },
  listContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 60,
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 80,
    gap: 16,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#333",
  },
  emptyText: {
    fontSize: 15,
    color: "#888",
    textAlign: "center",
    fontWeight: "500",
    lineHeight: 22,
  },
  card: {
    backgroundColor: "white",
    borderRadius: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: "#e9ecef",
    overflow: "hidden",
  },
  ongoingCard: {
    borderLeftWidth: 5,
    borderLeftColor: "#4CAF50",
    backgroundColor: "#F1F8F4",
    shadowColor: "#4CAF50",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  cancelledCard: {
    borderLeftWidth: 5,
    borderLeftColor: "#F44336",
  },
  cardTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    padding: 16,
    paddingBottom: 12,
  },
  dateContainer: {
    flex: 1,
  },
  dateText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1a1a1a",
    marginBottom: 3,
    textTransform: "capitalize",
  },
  timeText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#666",
  },
  paymentModeText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#757575",
    marginTop: 2,
  },
  statusBadgeContainer: {
    marginLeft: 12,
    gap: 6,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  statusBadgeCancelled: {
    backgroundColor: "#FFEBEE",
  },
  statusBadgePast: {
    backgroundColor: "#E0E0E0",
  },
  statusBadgeOngoing: {
    backgroundColor: "#4CAF50",
  },
  statusBadgeUpcoming: {
    backgroundColor: "#E3F2FD",
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: "800",
  },
  statusBadgeTextCancelled: {
    color: "#F44336",
  },
  statusBadgeTextPast: {
    color: "#757575",
  },
  statusBadgeTextOngoing: {
    color: "white",
  },
  statusBadgeTextUpcoming: {
    color: "#2196F3",
  },
  divider: {
    height: 1,
    backgroundColor: "#f0f0f0",
    marginHorizontal: 16,
  },
  cardContent: {
    padding: 14,
    paddingTop: 10,
    gap: 8,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  infoText: {
    fontSize: 13,
    color: "#333",
    fontWeight: "500",
  },
  infoRowMain: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  infoRowSub: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingLeft: 2,
  },
  userNameText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1a1a1a",
    flex: 1,
  },
  locationText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#666",
    flex: 1,
  },
  matchStatusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    marginTop: 4,
    alignSelf: "flex-start",
  },
  matchStatusText: {
    fontSize: 11,
    fontWeight: "700",
  },
  matchStatusBadgeInline: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    alignSelf: "flex-end",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
  },
  matchStatusTextInline: {
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  scoreButtonContainer: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: "#FFF8E1",
    borderTopWidth: 1,
    borderTopColor: "#FFE082",
  },
  scoreButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: "white",
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#FF9800",
    shadowColor: "#FF9800",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  scoreButtonText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#FF9800",
    letterSpacing: 0.3,
  },
  cardFooterBlue: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: "#2196F3",
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
  },
  priceContainerBlue: {
    gap: 2,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 70,
  },
  priceLabelBlue: {
    fontSize: 10,
    fontWeight: "600",
    color: "#fff",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  priceValueBlue: {
    fontSize: 16,
    fontWeight: "900",
    color: "#fff",
    marginTop: -2,
  },
  actionButtonBlue: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  actionButtonTextBlue: {
    fontSize: 12,
    fontWeight: "700",
    color: "#fff",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "flex-end",
  },
  modalOverlayCenter: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "white",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: "70%",
  },
  modalContentCenter: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 24,
    minWidth: 300,
    maxWidth: "90%",
    alignItems: "stretch",
    elevation: 8,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: "#1a1a1a",
  },
  optionsList: {
    maxHeight: 400,
  },
  optionItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f5f5f5",
  },
  optionItemSelected: {
    backgroundColor: "#E3F2FD",
  },
  optionText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
  },
  optionTextSelected: {
    color: "#2196F3",
    fontWeight: "800",
  },
  calendar: {
    borderRadius: 10,
    marginBottom: 20,
  },
  calendarContainer: {
    paddingHorizontal: 12,
    paddingBottom: 12,
  },
  clearDateButton: {
    alignSelf: "center",
    paddingVertical: 12,
    paddingHorizontal: 20,
    backgroundColor: "#F5F5F5",
    borderRadius: 8,
    marginBottom: 10,
  },
  clearDateText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#666",
  },
  filterModalOption: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 24,
    marginHorizontal: 12,
    backgroundColor: "transparent",
  },
  filterModalOptionWithBorder: {
    borderBottomWidth: 1,
    borderBottomColor: "#e8e8e8",
    marginBottom: 0,
  },
  filterModalOptionText: {
    fontSize: 16,
    color: "#333",
    fontWeight: "600",
  },
});
