@startuml
title GET /campo/:id

actor Client
participant Router
participant getCampoCalendarByMonth

Client -> Router: GET /campo/:id
Router -> getCampoCalendarByMonth: getCampoCalendarByMonth()
getCampoCalendarByMonth --> Router: response
Router --> Client: JSON
@enduml
