@startuml
title GET /struttura/:id

actor Client
participant Router
participant getCampiByStruttura

Client -> Router: GET /struttura/:id
Router -> getCampiByStruttura: getCampiByStruttura()
note right of getCampiByStruttura
params: { id }
end note
getCampiByStruttura --> Router: response
Router --> Client: JSON
@enduml
