@startuml
title PUT /strutture/:id

actor Client
participant Router
participant updateStruttura

Client -> Router: PUT /strutture/:id
Router -> updateStruttura: updateStruttura()
note right of updateStruttura
auth: user
end note
updateStruttura --> Router: response
Router --> Client: JSON
@enduml
