import { StyleSheet, Dimensions, Platform } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#f8f9fa",
  },

  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
  },
  loadingText: {
    fontSize: 16,
    color: "#666",
    fontWeight: "600",
  },

  container: {
    flex: 1,
  },

  imageContainer: {
    height: 280,
    position: "relative",
  },
  
  // ✅ NUOVO: ScrollView per carousel
  headerImageScroll: {
    width: "100%",
    height: "100%",
  },
  
  headerImage: {
    width: width,
    height: 280,
  },
  
  placeholderImage: {
    width: "100%",
    height: "100%",
    backgroundColor: "#e9ecef",
    alignItems: "center",
    justifyContent: "center",
  },
  
  imageOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  
  // ✅ NUOVO: Indicatori carousel
  pagination: {
    position: "absolute",
    bottom: 16,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "center",
    gap: 6,
    zIndex: 5,
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "rgba(255, 255, 255, 0.5)",
  },
  paginationDotActive: {
    backgroundColor: "white",
    width: 24,
  },
  
  backButton: {
    position: "absolute",
    top: 16,
    left: 16,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(0,0,0,0.5)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },
  
  statusBadge: {
    position: "absolute",
    top: 16,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    zIndex: 10,
  },
  statusConfirmed: {
    backgroundColor: "#4CAF50",
  },
  statusCancelled: {
    backgroundColor: "#F44336",
  },
  statusPast: {
    backgroundColor: "#757575",
  },
  statusBadgeText: {
    color: "white",
    fontSize: 13,
    fontWeight: "700",
  },

  content: {
    marginTop: -32,
    paddingHorizontal: 16,
  },

  // ==================== FIELD INFO CARD (VERSIONE COMPATTA PLAYER) ====================
  fieldInfoCard: {
    backgroundColor: "white",
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 12,
    padding: 16,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  fieldInfoHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 14,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  fieldInfoTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#1a1a1a",
    letterSpacing: -0.3,
  },
  fieldInfoList: {
    gap: 0,
  },
  fieldInfoRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingVertical: 10,
  },
  fieldInfoDivider: {
    height: 1,
    backgroundColor: "#f5f5f5",
    marginVertical: 4,
  },
  fieldIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#E3F2FD",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  fieldInfoContent: {
    flex: 1,
    gap: 3,
  },
  fieldInfoLabel: {
    fontSize: 9,
    color: "#999",
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  fieldInfoValue: {
    fontSize: 14,
    color: "#1a1a1a",
    fontWeight: "700",
    lineHeight: 19,
    letterSpacing: -0.2,
  },
  fieldInfoSubValue: {
    fontSize: 12,
    color: "#666",
    marginTop: 1,
    lineHeight: 17,
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  sportCampoGrid: {
    flexDirection: "row",
    gap: 10,
    paddingVertical: 8,
  },
  sportCampoColumn: {
    flex: 1,
  },
  sportCampoBox: {
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#f0f0f0",
    gap: 10,
  },
  mapButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: "#E3F2FD",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E3F2FD",
  },
  mapButtonText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#2196F3",
    letterSpacing: 0.2,
  },

  modernStatusCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    padding: 20,
  },
  modernStatusIconContainer: {
    width: 56,
    height: 56,
  },
  modernStatusIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#4CAF50",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  modernStatusContent: {
    flex: 1,
  },
  modernStatusText: {
    fontSize: 20,
    fontWeight: "900",
    marginBottom: 4,
  },
  modernStatusSubtext: {
    fontSize: 14,
    color: "#666",
    fontWeight: "600",
  },

  strutturaHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  sportIconBox: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#E3F2FD",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#2196F3",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  strutturaInfo: {
    flex: 1,
  },
  strutturaName: {
    fontSize: 20,
    fontWeight: "800",
    color: "#1a1a1a",
    marginBottom: 4,
  },
  campoName: {
    fontSize: 15,
    color: "#666",
    fontWeight: "500",
  },

  locationCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#f8f9fa",
    padding: 14,
    borderRadius: 12,
  },
  locationIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#FFEBEE",
    alignItems: "center",
    justifyContent: "center",
  },
  locationInfo: {
    flex: 1,
  },
  locationAddress: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
    marginBottom: 2,
  },
  locationCity: {
    fontSize: 13,
    color: "#666",
  },

  card: {
    backgroundColor: "white",
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 12,
    padding: 20,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1a1a1a",
    letterSpacing: -0.3,
  },

  clientCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#f8f9fa",
    padding: 14,
    borderRadius: 12,
  },
  clientInfoPressable: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  clientAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#2196F3",
    alignItems: "center",
    justifyContent: "center",
  },
  clientAvatarText: {
    fontSize: 20,
    fontWeight: "700",
    color: "white",
    letterSpacing: 0.5,
  },
  clientInfo: {
    flex: 1,
  },
  clientName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1a1a1a",
    marginBottom: 2,
  },
  clientEmail: {
    fontSize: 13,
    color: "#666",
  },
  chatButtonInline: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#E3F2FD",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
    shadowColor: "#2196F3",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  chatButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2196F3",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginVertical: 12,
    gap: 8,
    shadowColor: "#2196F3",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  chatButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "white",
  },
  groupChatButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "white",
    borderWidth: 2,
    borderColor: "#2196F3",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginVertical: 8,
    gap: 8,
    shadowColor: "#2196F3",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  groupChatButtonDisabled: {
    opacity: 0.6,
  },
  groupChatButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#2196F3",
  },

  dateTimeContainer: {
    flexDirection: "row",
    gap: 16,
  },
  dateBox: {
    width: 64,
    height: 64,
    backgroundColor: "#2196F3",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#2196F3",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  dateDay: {
    fontSize: 20,
    fontWeight: "800",
    color: "white",
  },
  dateMonth: {
    fontSize: 11,
    fontWeight: "700",
    color: "white",
    letterSpacing: 0.5,
  },
  dateDetails: {
    flex: 1,
    justifyContent: "center",
  },
  dateFullText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
    marginBottom: 6,
    textTransform: "capitalize",
  },
  timeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  timeText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#666",
  },

  matchResult: {
    gap: 16,
  },
  resultBadge: {
    alignSelf: "flex-start",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
  },
  winBadge: {
    backgroundColor: "#E8F5E9",
  },
  loseBadge: {
    backgroundColor: "#FFEBEE",
  },
  resultBadgeText: {
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.5,
    color: "#333",
  },

  setsContainer: {
    gap: 10,
  },
  setItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#f8f9fa",
    padding: 14,
    borderRadius: 12,
  },
  setLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: "#666",
  },
  setScore: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  setScoreText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#999",
    minWidth: 28,
    textAlign: "center",
  },
  setScoreWin: {
    color: "#4CAF50",
    fontSize: 20,
  },
  setScoreSeparator: {
    fontSize: 16,
    color: "#ccc",
  },

  insertResultCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    backgroundColor: "#E3F2FD",
    padding: 20,
    borderRadius: 16,
    marginBottom: 16,
    borderWidth: 2,
    borderColor: "#2196F3",
    borderStyle: "dashed",
    shadowColor: "#2196F3",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 3,
  },
  insertResultIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#2196F3",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  insertResultContent: {
    flex: 1,
  },
  insertResultTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#2196F3",
    marginBottom: 2,
  },
  insertResultSubtitle: {
    fontSize: 13,
    color: "#1976D2",
  },

  noResultBox: {
    padding: 24,
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
    alignItems: "center",
    gap: 8,
  },
  noResultText: {
    fontSize: 14,
    color: "#999",
    textAlign: "center",
    fontWeight: "500",
  },

  incassoBox: {
    backgroundColor: "#E8F5E9",
    padding: 20,
    borderRadius: 12,
    alignItems: "center",
  },
  incassoLabel: {
    fontSize: 13,
    color: "#2E7D32",
    fontWeight: "600",
    marginBottom: 8,
  },
  incassoAmount: {
    fontSize: 36,
    fontWeight: "800",
    color: "#4CAF50",
  },

  cancelButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#F44336",
    paddingVertical: 16,
    borderRadius: 12,
    marginHorizontal: 16,
    shadowColor: "#F44336",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "white",
  },

  // Match Info Styles
  matchStatusCard: {
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  matchStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  matchStatusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: "#e0e0e0",
  },
  matchStatusCompleted: {
    backgroundColor: "#E8F5E9",
  },
  matchStatusOpen: {
    backgroundColor: "#E3F2FD",
  },
  matchStatusFull: {
    backgroundColor: "#FFF3E0",
  },
  matchStatusCancelled: {
    backgroundColor: "#FFEBEE",
  },
  matchStatusText: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    color: "#666",
  },
  matchInfoRowContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  matchInfoItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  matchInfoText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#1a1a1a",
  },
  pendingBadge: {
    backgroundColor: "#FFF3E0",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  matchInfoBox: {
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
    padding: 16,
  },
  matchInfoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
  },
  matchInfoLabel: {
    fontSize: 14,
    color: "#666",
    fontWeight: "600",
  },
  matchInfoValue: {
    fontSize: 15,
    color: "#1a1a1a",
    fontWeight: "700",
  },

  // Teams Container
  teamsContainer: {
    gap: 16,
  },
  teamSection: {
    borderWidth: 1,
    borderColor: "#e8e8e8",
    borderRadius: 14,
    backgroundColor: "white",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  teamHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.2)",
  },
  teamTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "white",
    letterSpacing: -0.2,
  },
  teamSectionPlayer: {
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  teamHeaderPlayer: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    gap: 8,
  },
  teamTitlePlayer: {
    fontSize: 15,
    fontWeight: "700",
    flex: 1,
  },
  teamHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  teamCountPlayer: {
    fontSize: 13,
    fontWeight: "600",
  },
  teamSlotsContainer: {
    padding: 12,
    gap: 8,
  },
  playerSlot: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
    gap: 12,
  },
  emptySlotInvite: {
    backgroundColor: "#E3F2FD",
    borderWidth: 2,
    borderColor: "#2196F3",
    borderStyle: "dashed",
  },
  inviteAvatarCircle: {
    backgroundColor: "white",
  },
  playerAvatarCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#2196F3",
    alignItems: "center",
    justifyContent: "center",
  },
  playerInitials: {
    fontSize: 14,
    fontWeight: "800",
    color: "white",
  },
  playerInfoSlot: {
    flex: 1,
  },
  playerNameSlot: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1a1a1a",
    marginBottom: 2,
  },
  playerUsernameSlot: {
    fontSize: 12,
    color: "#666",
  },

  // Team Styles
  teamSection: {
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
    padding: 12,
  },
  teamHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#e9ecef",
  },
  teamHeaderText: {
    flex: 1,
    fontSize: 15,
    fontWeight: "800",
    color: "#1a1a1a",
  },
  teamCount: {
    fontSize: 13,
    fontWeight: "700",
    color: "#666",
  },
  playerCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "white",
    padding: 12,
    borderRadius: 10,
    marginBottom: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  playerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#E3F2FD",
    alignItems: "center",
    justifyContent: "center",
  },
  playerInitials: {
    fontSize: 14,
    fontWeight: "800",
    color: "#2196F3",
  },
  playerInfo: {
    flex: 1,
  },
  playerName: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1a1a1a",
    marginBottom: 2,
  },
  playerUsername: {
    fontSize: 12,
    color: "#666",
    fontWeight: "500",
  },
  teamBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  teamBadgeText: {
    fontSize: 13,
    fontWeight: "900",
  },
  noPlayersText: {
    textAlign: "center",
    color: "#999",
    fontSize: 13,
    fontWeight: "500",
    fontStyle: "italic",
    paddingVertical: 12,
  },

  // Unassigned & Pending Players
  unassignedSection: {
    backgroundColor: "white",
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  unassignedTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#333",
    marginBottom: 4,
  },
  unassignedSubtitle: {
    fontSize: 13,
    color: "#666",
    marginBottom: 16,
  },
  pendingSection: {
    backgroundColor: "white",
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  pendingTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#333",
    marginBottom: 4,
  },
  pendingSubtitle: {
    fontSize: 13,
    color: "#666",
    marginBottom: 16,
  },
  playersGrid: {
    gap: 12,
  },

  // Empty Team Card
  emptyTeamCard: {
    padding: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
    margin: 12,
  },
  emptyTeamText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#999",
    marginTop: 8,
  },
  emptyTeamHint: {
    fontSize: 12,
    color: "#bbb",
    marginTop: 4,
    textAlign: "center",
  },

  // Score Display Styles
  scoreDisplayCard: {
    backgroundColor: "#FFF",
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  scoreDisplayHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  scoreDisplayHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  scoreDisplayTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1a1a1a",
    letterSpacing: -0.3,
  },
  scoreDisplaySubtitle: {
    fontSize: 13,
    color: "#666",
    marginTop: 2,
  },
  scoreMainDisplay: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingVertical: 20,
    backgroundColor: "#f8f9fa",
    borderRadius: 14,
    marginBottom: 20,
  },
  scoreTeamDisplay: {
    alignItems: "center",
    gap: 12,
  },
  scoreTeamBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 16,
  },
  scoreTeamAvatars: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: -6,
  },
  scoreAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#2196F3",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#FFF",
    marginLeft: -6,
  },
  scoreAvatarText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#FFF",
    letterSpacing: 0.2,
  },
  scoreTeamBadgeWinner: {
    backgroundColor: "#FFF8E1",
    borderWidth: 2,
    borderColor: "#FFD700",
  },
  scoreTeamName: {
    fontSize: 13,
    fontWeight: "800",
    color: "#FFF",
    letterSpacing: 0.4,
  },
  scoreTeamScore: {
    fontSize: 48,
    fontWeight: "900",
    color: "#666",
    letterSpacing: -1.5,
  },
  scoreTeamScoreWinner: {
    color: "#FFD700",
  },
  scoreWinnerLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: "#FFD700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  scoreDivider: {
    alignItems: "center",
    justifyContent: "center",
  },
  winnerIndicator: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: 12,
    borderRadius: 12,
    marginBottom: 20,
  },
  winnerIndicatorText: {
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  setsDetailContainer: {
    backgroundColor: "#FFF",
  },
  setsDetailTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#1a1a1a",
    marginBottom: 12,
    letterSpacing: -0.2,
  },
  setsDetailList: {
    gap: 8,
  },
  setDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 12,
    backgroundColor: "#f9f9f9",
    borderRadius: 10,
  },
  setDetailNumber: {
    fontSize: 13,
    fontWeight: "700",
    color: "#666",
    width: 50,
    letterSpacing: 0.2,
  },
  setDetailScore: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
    justifyContent: "center",
  },
  setDetailTeamScore: {
    fontSize: 20,
    fontWeight: "800",
    color: "#999",
    letterSpacing: -0.4,
  },
  setDetailTeamScoreWinner: {
    color: "#4CAF50",
  },
  setDetailDivider: {
    fontSize: 18,
    color: "#CCC",
    fontWeight: "700",
  },
  setDetailWinner: {
    width: 40,
    alignItems: "flex-end",
  },
  setDetailWinnerBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  setDetailWinnerBadgeA: {
    backgroundColor: "#E3F2FD",
  },
  setDetailWinnerBadgeB: {
    backgroundColor: "#FFEBEE",
  },
  setDetailWinnerText: {
    fontSize: 14,
    fontWeight: "900",
    color: "#FFF",
  },
  // ==================== MODAL ====================
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "white",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    maxHeight: "75%",
    marginHorizontal: 10,
    marginBottom: 10,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -3 },
        shadowOpacity: 0.12,
        shadowRadius: 10,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 20,
    paddingBottom: 24,
    backgroundColor: "#667eea",
    borderBottomWidth: 0,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "white",
    letterSpacing: -0.3,
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  modalCloseButton: {
    padding: 8,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.2)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
  },
  modalBody: {
    padding: 20,
  },
  profileHeader: {
    alignItems: "center",
    paddingVertical: 24,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
    marginBottom: 20,
  },
  profileAvatarLarge: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "#2196F3",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    shadowColor: "#2196F3",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  profileAvatarTextLarge: {
    fontSize: 36,
    fontWeight: "700",
    color: "white",
    letterSpacing: 1,
  },
  profileName: {
    fontSize: 24,
    fontWeight: "700",
    color: "#1a1a1a",
    marginBottom: 4,
    textAlign: "center",
  },
  profileUsername: {
    fontSize: 16,
    color: "#666",
    fontWeight: "500",
  },
  profileSection: {
    marginBottom: 24,
  },
  profileSectionTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#666",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 12,
  },
  profileInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
    marginBottom: 8,
  },
  profileInfoTextContainer: {
    marginLeft: 12,
    flex: 1,
  },
  profileInfoLabel: {
    fontSize: 12,
    color: "#999",
    marginBottom: 2,
    fontWeight: "500",
  },
  profileInfoText: {
    fontSize: 15,
    color: "#1a1a1a",
    fontWeight: "600",
    marginLeft: 12,
    flex: 1,
  },
  profileActions: {
    marginTop: 8,
    marginBottom: 20,
  },
  profileActionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2196F3",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginBottom: 12,
    gap: 8,
  },
  profileActionButtonSecondary: {
    backgroundColor: "white",
    borderWidth: 2,
    borderColor: "#2196F3",
  },
  profileActionButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "white",
  },
  profileActionButtonTextSecondary: {
    color: "#2196F3",
  },
  setDetailTieText: {
    fontSize: 13,
    color: "#CCC",
    fontWeight: "700",
  },
  
  // Floating Add Button
  floatingAddButton: {
    position: "absolute",
    bottom: 24,
    right: 24,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#4CAF50",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },

  // ==================== CARD GENERALE ====================
  card: {
    backgroundColor: "white",
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 20,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1a1a1a",
    letterSpacing: -0.3,
  },

  // ==================== MATCH SECTION ====================
  matchHeaderActions: {
    flexDirection: "row",
    gap: 8,
  },
  groupChatButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#2196F3",
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 10,
    marginRight: 8,
    shadowColor: "#2196F3",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  groupChatButtonText: {
    color: "white",
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0.2,
  },

  // ==================== MATCH STATUS ====================
  matchStatusCard: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  matchStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  matchStatusLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  matchStatusIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  matchStatusTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1a1a1a",
    letterSpacing: -0.2,
  },
  matchStatusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  matchStatusCompleted: {
    backgroundColor: "#4CAF50",
  },
  matchStatusOpen: {
    backgroundColor: "#2196F3",
  },
  matchStatusFull: {
    backgroundColor: "#FF9800",
  },
  matchStatusCancelled: {
    backgroundColor: "#F44336",
  },
  matchStatusInProgress: {
    backgroundColor: "#FF5722",
  },
  matchStatusText: {
    fontSize: 11,
    fontWeight: "700",
    color: "white",
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  matchStatsCompact: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginTop: 8,
  },
  matchStatItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  matchStatIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  matchStatText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#1a1a1a",
  },

  // ==================== TEAMS ====================
  teamsContainer: {
    gap: 12,
    marginBottom: 16,
  },
  teamSection: {
    borderWidth: 1,
    borderColor: "#e8e8e8",
    borderRadius: 14,
    backgroundColor: "white",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  teamHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.2)",
  },
  teamTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "white",
    letterSpacing: -0.2,
  },
  teamHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  teamCount: {
    fontSize: 14,
    fontWeight: "800",
    color: "white",
    letterSpacing: 0.2,
  },
  teamSlotsContainer: {
    padding: 12,
    gap: 10,
  },

  // ==================== UNASSIGNED & PENDING ====================
  unassignedSection: {
    backgroundColor: "#FFF8E1",
    padding: 16,
    borderRadius: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#FFE082",
  },
  unassignedTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#1a1a1a",
    marginBottom: 4,
    letterSpacing: -0.2,
  },
  unassignedSubtitle: {
    fontSize: 13,
    color: "#666",
    marginBottom: 14,
    lineHeight: 18,
  },
  pendingSection: {
    backgroundColor: "#F5F5F5",
    padding: 16,
    borderRadius: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  pendingTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#1a1a1a",
    marginBottom: 14,
    letterSpacing: -0.2,
  },
  playersGrid: {
    gap: 10,
  },

  // ==================== MODAL ====================
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  centeredModalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    backgroundColor: "white",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    maxHeight: "75%",
    marginHorizontal: 10,
    marginBottom: 10,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -3 },
        shadowOpacity: 0.12,
        shadowRadius: 10,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 20,
    paddingBottom: 24,
    backgroundColor: "#667eea",
    borderBottomWidth: 0,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "white",
    letterSpacing: -0.3,
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  modalCloseButton: {
    padding: 8,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.2)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
  },

  // Search
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 16,
    marginTop: -8,
    marginBottom: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: "white",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e8f0fe",
    gap: 12,
    ...Platform.select({
      ios: {
        shadowColor: "#667eea",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 6,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: "#1a1a1a",
    fontWeight: "500",
    paddingVertical: 0,
  },

  // Search Results
  searchResults: {
    paddingHorizontal: 16,
    paddingBottom: 20,
  },
  searchResultItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginVertical: 4,
    backgroundColor: "#fafbfc",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#f0f2f5",
  },
  resultAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: "#e8f0fe",
  },
  resultAvatarPlaceholder: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#f0f2f5",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#e8f0fe",
  },
  resultInfo: {
    flex: 1,
    marginLeft: 14,
  },
  resultName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1a1a1a",
    letterSpacing: -0.1,
  },
  resultUsername: {
    fontSize: 14,
    color: "#667eea", // Questo sarà sovrascritto dinamicamente
    marginTop: 2,
    fontWeight: "500",
  },
  noResults: {
    textAlign: "center",
    fontSize: 16,
    color: "#999",
    marginTop: 40,
    fontWeight: "500",
    paddingVertical: 20,
  },
});