@startuml
skinparam Style strictuml
skinparam sequence {
  ParticipantPadding 30
  MessageAlign center
}

title GET /search-address

actor Client
participant "Express Router" as Router
participant "searchAddress" as Controller
database MongoDB

Client -> Router: GET /search-address
activate Router
Router -> Controller: searchAddress()
activate Controller

autonumber
note over Controller: Validate Input / Check Existence

alt success
  Controller --> Client: res.json(data)
else catch (error)
  Controller --> Client: res.status(500)
end

deactivate Controller
Router --> Client: HTTP Response
deactivate Router
@enduml
