import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#f8f9fa",
  },
  header: {
    backgroundColor: "white",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 7,
    borderBottomWidth: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  headerTitle: {
    fontSize: 18,
    textAlign: "center",
    fontWeight: "700",
    color: "#1a1a1a",
    marginBottom: 14,
  },
  filterContainer: {
    flexDirection: "row",
    gap: 8,
  },
  filterButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: "#f5f5f5",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "transparent",
  },
  filterButtonActive: {
    backgroundColor: "#2196F3",
    borderColor: "#2196F3",
    shadowColor: "#2196F3",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  filterButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  filterButtonText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#666",
  },
  filterButtonTextActive: {
    color: "white",
    fontWeight: "700",
  },
  struttureFilterContainer: {
    marginTop: 12,
  },
  strutturaChipSelector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: "#E8F5E9",
    borderWidth: 1.5,
    borderColor: "#4CAF50",
  },
  strutturaChipContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  strutturaChipSelectorText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#2E7D32",
    flex: 1,
  },
  listContent: {
    padding: 16,
  },
  conversationCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "white",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 0,
    borderLeftWidth: 3,
    borderLeftColor: "transparent",
  },
  conversationCardUnread: {
    borderLeftColor: "#2196F3",
    backgroundColor: "#FAFFFE",
    shadowColor: "#2196F3",
    shadowOpacity: 0.12,
  },
  conversationLeft: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    flex: 1,
  },
  avatarContainer: {
    position: "relative",
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#E3F2FD",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#2196F3",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  unreadDot: {
    position: "absolute",
    top: -2,
    right: -2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: "#FF5252",
    borderWidth: 2.5,
    borderColor: "white",
  },
  conversationImage: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#f0f0f0",
  },
  conversationImagePlaceholder: {
    justifyContent: "center",
    alignItems: "center",
  },
  conversationInfo: {
    flex: 1,
    gap: 3,
  },
  conversationHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 2,
  },
  conversationTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#1a1a1a",
    flex: 1,
  },
  conversationTitleUnread: {
    fontWeight: "700",
    color: "#000",
  },
  conversationTime: {
    fontSize: 11,
    color: "#999",
    fontWeight: "500",
    marginLeft: 8,
  },
  strutturaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 3,
  },
  strutturaName: {
    fontSize: 12,
    color: "#666",
    fontWeight: "500",
    flex: 1,
  },
  conversationSubtitle: {
    fontSize: 13,
    color: "#666",
    fontWeight: "500",
  },
  conversationLastMessage: {
    fontSize: 13,
    color: "#999",
    lineHeight: 18,
  },
  conversationLastMessageUnread: {
    fontWeight: "600",
    color: "#333",
  },
  conversationMessage: {
    fontSize: 14,
    color: "#999",
    marginTop: 4,
  },
  matchInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#E3F2FD",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  matchInfoText: {
    fontSize: 11,
    color: "#2196F3",
    fontWeight: "600",
  },
  groupDetailsContainer: {
    marginTop: 2,
    marginBottom: 4,
  },
  groupDetailsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
  },
  groupDetailText: {
    fontSize: 11,
    color: "#666",
    fontWeight: "500",
  },
  unreadBadge: {
    backgroundColor: "#FF5252",
    minWidth: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 8,
    marginLeft: 8,
    shadowColor: "#FF5252",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 3,
  },
  unreadBadgeText: {
    color: "white",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  unreadText: {
    color: "white",
    fontSize: 12,
    fontWeight: "700",
  },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 40,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#333",
    marginTop: 16,
    marginBottom: 8,
  },
  emptyText: {
    fontSize: 15,
    color: "#999",
    textAlign: "center",
    lineHeight: 22,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
  },
  loadingText: {
    fontSize: 14,
    color: "#666",
    fontWeight: "500",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "white",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "80%",
    paddingBottom: 20,
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: "#E0E0E0",
    borderRadius: 2,
    alignSelf: "center",
    marginTop: 12,
    marginBottom: 8,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1a1a1a",
  },
  modalList: {
    maxHeight: 400,
  },
  modalItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f5f5f5",
  },
  modalItemActive: {
    backgroundColor: "#F1F8F4",
  },
  modalItemLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  modalItemIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#E8F5E9",
    justifyContent: "center",
    alignItems: "center",
  },
  modalItemIconActive: {
    backgroundColor: "#4CAF50",
  },
  modalItemText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
  },
  modalItemTextActive: {
    color: "#2E7D32",
    fontWeight: "700",
  },
  modalItemSubtext: {
    fontSize: 12,
    color: "#999",
    marginTop: 2,
  },
});