import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#f8f9fa",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1a1a1a",
  },
  settingsButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f8f9fa",
  },
  loading: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: 16,
  },
  loadingText: {
    fontSize: 16,
    color: "#999",
  },
  hero: {
    backgroundColor: "#fff",
    padding: 20,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 5,
  },
  // Layout stile Instagram migliorato
  instagramHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingBottom: 16,
  },
  avatarContainer: {
    position: "relative",
    marginRight: 24,
  },
  instagramStats: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingHorizontal: 8,
  },
  instagramStatItem: {
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 4,
    borderRadius: 8,
  },
  instagramStatItemPressed: {
    backgroundColor: "#f0f0f0",
    transform: [{ scale: 0.95 }],
  },
  instagramStatValue: {
    fontSize: 20,
    fontWeight: "800",
    color: "#1a1a1a",
    letterSpacing: 0.3,
  },
  instagramStatLabel: {
    fontSize: 11,
    color: "#8e8e8e",
    marginTop: 3,
    fontWeight: "500",
  },
  instagramBio: {
    paddingTop: 4,
    borderTopWidth: 1,
    borderTopColor: "#efefef",
    paddingBottom: 4,
  },
  instagramName: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1a1a1a",
    letterSpacing: 0.2,
  },
  instagramUsername: {
    fontSize: 13,
    color: "#8e8e8e",
    marginTop: 3,
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    overflow: "hidden",
    borderWidth: 3,
    borderColor: "#ef8f00",
  },
  // ✅ NUOVO: per mostrare l'immagine avatar
  avatarImage: {
    width: "100%",
    height: "100%",
  },
  // ✅ NUOVO: placeholder quando non c'è immagine
  avatarPlaceholder: {
    width: "100%",
    height: "100%",
    backgroundColor: "#ef8f00",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: {
    fontSize: 32,
    fontWeight: "700",
    color: "#fff",
  },
  editAvatarButton: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: "#ef8f00",
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: "#fff",
    shadowColor: "#ef8f00",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  privateBadge: {
    position: "absolute",
    top: 0,
    right: 0,
    backgroundColor: "#fff",
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#e0e0e0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
  },
  name: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1a1a1a",
    lineHeight: 22,
  },
  surname: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1a1a1a",
    marginBottom: 2,
    lineHeight: 22,
  },
  username: {
    fontSize: 13,
    color: "#666",
  },
  stats: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingTop: 20,
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: "#fff",
    padding: 16,
    borderRadius: 16,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  dualStatRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    marginTop: 6,
  },
  dualStatCell: {
    flex: 1,
    alignItems: "center",
  },
  dualStatDivider: {
    width: 1,
    height: 24,
    backgroundColor: "#eee",
  },
  statIconBox: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
    position: "relative",
  },
  statBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    backgroundColor: "#F44336",
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 6,
    borderWidth: 2,
    borderColor: "#fff",
  },
  statBadgeText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "700",
  },
  statValue: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1a1a1a",
    marginBottom: 2,
  },
  statLabel: {
    fontSize: 12,
    color: "#666",
  },
  favorite: {
    margin: 16,
    backgroundColor: "#fff",
    padding: 16,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  favoriteHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  favoriteTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#666",
  },
  favoriteName: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1a1a1a",
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1a1a1a",
    paddingHorizontal: 16,
    marginTop: 8,
    marginBottom: 12,
  },
  card: {
    marginHorizontal: 16,
    backgroundColor: "#fff",
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    gap: 12,
  },
  menuIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
  },
  menuTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1a1a1a",
    marginBottom: 2,
  },
  menuSubtitle: {
    fontSize: 13,
    color: "#999",
  },
  divider: {
    height: 1,
    backgroundColor: "#f0f0f0",
    marginLeft: 72,
  },
  prefRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    gap: 12,
  },
  prefIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  logout: {
    marginHorizontal: 16,
    marginTop: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: 16,
    backgroundColor: "#fff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#ffe5e5",
  },
  logoutText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#F44336",
  },
  version: {
    textAlign: "center",
    fontSize: 13,
    color: "#999",
    marginTop: 20,
  },
  // Compact stats dentro hero
  compactStats: {
    flexDirection: "column",
    gap: 6,
  },
  compactStatCard: {
    backgroundColor: "#f8f9fa",
    borderRadius: 10,
    padding: 8,
    minWidth: 110,
  },
  compactStatRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  compactStatCell: {
    flex: 1,
    alignItems: "center",
  },
  compactStatDivider: {
    width: 1,
    height: 18,
    backgroundColor: "#e0e0e0",
  },
  compactStatValue: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1a1a1a",
    marginBottom: 1,
  },
  compactStatLabel: {
    fontSize: 10,
    color: "#666",
  },
  compactChatRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    position: "relative",
    justifyContent: "center",
  },
  compactChatInfo: {
    alignItems: "center",
  },
  compactBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    backgroundColor: "#F44336",
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 4,
  },
  compactBadgeText: {
    color: "#fff",
    fontSize: 8,
    fontWeight: "700",
  },
});
