import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#f8f9fa",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "rgba(255, 255, 255, 0.98)",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(33, 150, 243, 0.1)",
  },
  backButton: {
    padding: 6,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1a1a1a",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
  },
  errorText: {
    fontSize: 16,
    color: "#666",
    marginTop: 16,
    textAlign: "center",
  },
  scrollView: {
    flex: 1,
  },
  profileCard: {
    backgroundColor: "white",
    padding: 20,
    margin: 12,
    borderRadius: 20,
    alignItems: "center",
    shadowColor: "#2196F3",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(33, 150, 243, 0.08)',
  },
  avatarContainer: {
    marginBottom: 12,
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
  },
  avatarPlaceholder: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "#E3F2FD",
    justifyContent: "center",
    alignItems: "center",
  },
  name: {
    fontSize: 20,
    fontWeight: "800",
    color: "#1a1a1a",
    marginTop: 8,
    letterSpacing: 0.3,
  },
  username: {
    fontSize: 14,
    color: "#666",
    marginTop: 4,
  },
  followsYouBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: "#E8F5E9",
    borderRadius: 16,
    marginTop: 6,
    borderWidth: 1,
    borderColor: "#4CAF50",
  },
  followsYouText: {
    fontSize: 12,
    color: "#4CAF50",
    fontWeight: "600",
  },
  incomingRequestBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: "#FCE4EC",
    borderRadius: 16,
    marginTop: 6,
    borderWidth: 1,
    borderColor: "#E91E63",
  },
  incomingRequestText: {
    fontSize: 12,
    color: "#E91E63",
    fontWeight: "600",
  },
  statsContainer: {
    flexDirection: "column",
    gap: 12,
    marginTop: 16,
    marginBottom: 16,
    width: '100%',
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    gap: 32,
  },
  statItem: {
    alignItems: "center",
  },
  statValue: {
    fontSize: 20,
    fontWeight: "800",
    color: "#2196F3",
    letterSpacing: 0.3,
  },
  statLabel: {
    fontSize: 12,
    color: "#666",
    marginTop: 4,
    fontWeight: "500",
  },
  currentUserBadge: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    backgroundColor: "#E3F2FD",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#2196F3",
  },
  currentUserText: {
    fontSize: 13,
    color: "#2196F3",
    fontWeight: "600",
  },
  friendBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: "#E8F5E9",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#4CAF50",
  },
  friendBadgeText: {
    fontSize: 13,
    color: "#4CAF50",
    fontWeight: "600",
  },
  pendingBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: "#FFF3E0",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#FF9800",
  },
  pendingBadgeText: {
    fontSize: 13,
    color: "#FF9800",
    fontWeight: "600",
  },
  addFriendButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: "#2196F3",
    borderRadius: 12,
    shadowColor: "#2196F3",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  addFriendButtonDisabled: {
    opacity: 0.6,
  },
  addFriendButtonText: {
    fontSize: 14,
    color: "#fff",
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  chatButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: "transparent",
    borderWidth: 2,
    borderColor: "#2196F3",
    borderRadius: 12,
    marginTop: 10,
  },
  chatButtonText: {
    fontSize: 14,
    color: "#2196F3",
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  privateBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    padding: 4,
    borderWidth: 2,
    borderColor: '#fff',
  },
  privateWarning: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: '#F5F9FF',
    borderRadius: 12,
    marginTop: 12,
    borderWidth: 1,
    borderColor: 'rgba(33, 150, 243, 0.15)',
  },
  privateWarningText: {
    fontSize: 13,
    color: '#666',
    flex: 1,
  },

  // Posts Section
  postsSection: {
    marginTop: 8,
    marginBottom: 16,
  },
  postsSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: 'transparent',
  },
  postsSectionTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#1a1a1a',
    letterSpacing: 0.3,
  },
  postCard: {
    backgroundColor: '#F5F9FF',
    borderRadius: 12,
    marginBottom: 12,
    marginHorizontal: 12,
    padding: 14,
    shadowColor: '#2196F3',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: 'rgba(33, 150, 243, 0.15)',
  },
  postHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  postHeaderText: {
    marginLeft: 10,
    flex: 1,
  },
  postAuthor: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1a1a1a',
  },
  postTime: {
    fontSize: 11,
    color: '#999',
    marginTop: 2,
  },
  postContent: {
    fontSize: 14,
    color: '#333',
    lineHeight: 20,
    marginBottom: 10,
  },
  postImage: {
    width: '100%',
    height: 180,
    borderRadius: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(33, 150, 243, 0.1)',
  },
  postStats: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(33, 150, 243, 0.15)',
  },
  postStat: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  postStatText: {
    fontSize: 13,
    color: '#666',
    fontWeight: '500',
  },
  emptyPosts: {
    backgroundColor: '#F5F9FF',
    padding: 40,
    alignItems: 'center',
    borderRadius: 12,
    marginHorizontal: 12,
    borderWidth: 1,
    borderColor: 'rgba(33, 150, 243, 0.15)',
  },
  emptyPostsText: {
    fontSize: 13,
    color: '#999',
    marginTop: 10,
  },

  // Stats Cards
  statsCardsContainer: {
    flexDirection: 'row',
    gap: 8,
    width: '100%',
    marginTop: 14,
    marginBottom: 10,
  },
  statsCard: {
    flex: 1,
    backgroundColor: '#F5F9FF',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(33, 150, 243, 0.15)',
  },
  statsCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 8,
  },
  statsCardTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1a1a1a',
  },
  statsCardContent: {
    flexDirection: 'row',
    gap: 6,
  },
  statsCardItem: {
    flex: 1,
    alignItems: 'center',
  },
  statsCardValue: {
    fontSize: 18,
    fontWeight: '800',
    color: '#2196F3',
    letterSpacing: 0.3,
  },
  statsCardLabel: {
    fontSize: 10,
    color: '#666',
    marginTop: 2,
    fontWeight: '500',
  },
  statsCardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    marginTop: 6,
  },
  statsCardLink: {
    fontSize: 11,
    color: '#2196F3',
    fontWeight: '600',
  },
});
