import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1a1a1a",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
  },
  errorText: {
    fontSize: 16,
    color: "#666",
    marginTop: 16,
    textAlign: "center",
  },
  scrollView: {
    flex: 1,
  },
  profileCard: {
    backgroundColor: "white",
    padding: 24,
    margin: 16,
    borderRadius: 16,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  avatarContainer: {
    marginBottom: 16,
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
  },
  avatarPlaceholder: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "#E3F2FD",
    justifyContent: "center",
    alignItems: "center",
  },
  name: {
    fontSize: 24,
    fontWeight: "700",
    color: "#1a1a1a",
    marginTop: 8,
  },
  username: {
    fontSize: 16,
    color: "#666",
    marginTop: 4,
  },
  followsYouBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "#E8F5E9",
    borderRadius: 12,
    marginTop: 8,
  },
  followsYouText: {
    fontSize: 13,
    color: "#4CAF50",
    fontWeight: "600",
  },
  incomingRequestBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "#FCE4EC",
    borderRadius: 12,
    marginTop: 8,
  },
  incomingRequestText: {
    fontSize: 13,
    color: "#E91E63",
    fontWeight: "600",
  },
  statsContainer: {
    flexDirection: "column",
    gap: 16,
    marginTop: 24,
    marginBottom: 24,
    width: '100%',
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    gap: 32,
  },
  statItem: {
    alignItems: "center",
  },
  statValue: {
    fontSize: 24,
    fontWeight: "700",
    color: "#2196F3",
  },
  statLabel: {
    fontSize: 14,
    color: "#666",
    marginTop: 4,
  },
  currentUserBadge: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: "#E3F2FD",
    borderRadius: 8,
  },
  currentUserText: {
    fontSize: 14,
    color: "#2196F3",
    fontWeight: "600",
  },
  friendBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: "#E8F5E9",
    borderRadius: 8,
  },
  friendBadgeText: {
    fontSize: 14,
    color: "#4CAF50",
    fontWeight: "600",
  },
  pendingBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: "#FFF3E0",
    borderRadius: 8,
  },
  pendingBadgeText: {
    fontSize: 14,
    color: "#FF9800",
    fontWeight: "600",
  },
  addFriendButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: "#2196F3",
    borderRadius: 12,
  },
  addFriendButtonDisabled: {
    opacity: 0.6,
  },
  addFriendButtonText: {
    fontSize: 16,
    color: "#fff",
    fontWeight: "600",
  },
  privateBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    padding: 4,
    borderWidth: 2,
    borderColor: '#fff',
  },
  privateWarning: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    marginTop: 16,
  },
  privateWarningText: {
    fontSize: 14,
    color: '#666',
    flex: 1,
  },

  // Posts Section
  postsSection: {
    marginTop: 8,
    marginHorizontal: 16,
    marginBottom: 16,
  },
  postsSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: 'white',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  postsSectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a1a1a',
  },
  postCard: {
    backgroundColor: 'white',
    padding: 16,
    marginTop: 1,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  postHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  postHeaderText: {
    marginLeft: 12,
    flex: 1,
  },
  postAuthor: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1a1a1a',
  },
  postTime: {
    fontSize: 12,
    color: '#999',
    marginTop: 2,
  },
  postContent: {
    fontSize: 15,
    color: '#1a1a1a',
    lineHeight: 22,
    marginBottom: 12,
  },
  postImage: {
    width: '100%',
    height: 250,
    borderRadius: 12,
    marginBottom: 12,
    backgroundColor: '#f0f0f0',
  },
  postStats: {
    flexDirection: 'row',
    gap: 20,
  },
  postStat: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  postStatText: {
    fontSize: 14,
    color: '#666',
  },
  emptyPosts: {
    backgroundColor: 'white',
    padding: 48,
    alignItems: 'center',
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
  },
  emptyPostsText: {
    fontSize: 14,
    color: '#999',
    marginTop: 12,
  },

  // Stats Cards
  statsCardsContainer: {
    flexDirection: 'row',
    gap: 10,
    width: '100%',
    marginTop: 20,
    marginBottom: 12,
  },
  statsCard: {
    flex: 1,
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    padding: 14,
  },
  statsCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 10,
  },
  statsCardTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1a1a1a',
  },
  statsCardContent: {
    flexDirection: 'row',
    gap: 8,
  },
  statsCardItem: {
    flex: 1,
    alignItems: 'center',
  },
  statsCardValue: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1a1a1a',
  },
  statsCardLabel: {
    fontSize: 11,
    color: '#666',
    marginTop: 2,
  },
  statsCardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    marginTop: 8,
  },
  statsCardLink: {
    fontSize: 12,
    color: '#2196F3',
    fontWeight: '500',
  },
});
